[client]
log = ""
source = ""
archive = ""
key = ""
pattern = ""
extension = ""

[server]
host = ""
user = ""
port = ""
upload_dir = ""

[smtp]
host = "smtp.gmail.com"
port = 465
user = ""
password = ""
recipient = ""